install	:
	pip install -r requirements.txt

cleandep:
	pipreqs --clean requirements.txt

getdep: 
	pipreqs --savepath requirements.txt --force .

clean:
	find . -name "__pycache__" -type d -exec rm -rf {} +
	find . -name "*.pyc" -type f -delete