player_name = my_player.py
src_file = src_2147174_2117902

install	:
	pip install -r requirements.txt

cleandep:
	pipreqs --clean requirements.txt

getdep: 
	pipreqs --savepath requirements.txt --force .

clean:
	rm  *.json
	rm  data/*.json 
	
move:
	mv *.json data/

abyss:
	cp Divercite/${player_name} ./
	mkdir ${src_file}
	cp Divercite/${src_file}/*.py ./${src_file}
	zip abyss_2147174_2117902.zip requirements.txt ${player_name} ${src_file}/*.py
	rm ${player_name} ${src_file} -f -R

hvp:
	python Divercite/main_divercite.py -t human_vs_computer Divercite/${player_name}

hvr:
	python Divercite/main_divercite.py -t human_vs_computer Divercite/random_player_divercite.py

hvg:
	python Divercite/main_divercite.py -t human_vs_computer Divercite/greedy_player_divercite.py

gvp:
	python Divercite/main_divercite.py -t local Divercite/greedy_player_divercite.py Divercite/${player_name} -r -g

pvg:
	python Divercite/main_divercite.py -t local Divercite/${player_name} Divercite/greedy_player_divercite.py  -r -g

pvh:
	cd Divercite && python main_divercite.py -t human_vs_computer ${player_name}

pvr:
	python Divercite/main_divercite.py -t local Divercite/${player_name} Divercite/random_player_divercite.py  -r -g
